"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { RefreshCw, Search } from "lucide-react";
import { marketApi } from "@/lib/api";
import { Detail, Opportunity } from "@/types/market";
const WorldMap=dynamic(()=>import("./WorldMap"),{ssr:false,loading:()=> <div className="loading">正在加载地图…</div>});
const TrendChart=dynamic(()=>import("./TrendChart"),{ssr:false});
const money=(v:number)=>v>=1e9?`$${(v/1e9).toFixed(1)}B`:`$${(v/1e6).toFixed(0)}M`;
const pct=(v:number|null)=>v===null?"—":`${v>=0?"+":""}${(v*100).toFixed(1)}%`;

export default function MarketWorkspace({initialHs="902620",heading=true}:{initialHs?:string;heading?:boolean}){const [hs,setHs]=useState(initialHs);const [query,setQuery]=useState(initialHs);const [rows,setRows]=useState<Opportunity[]>([]);const [detail,setDetail]=useState<Detail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
const select=useCallback(async(id:number)=>{try{setDetail(await marketApi.detail(id))}catch(e){setError(e instanceof Error?e.message:"无法加载市场详情")}},[]);
const load=useCallback(async(code:string)=>{setLoading(true);setError("");try{let data=await marketApi.opportunities(code);if(!data.length){const run=await marketApi.createAnalysis(code);for(let i=0;i<20;i++){await new Promise(r=>setTimeout(r,500));const state=await marketApi.analysis(run.id);if(state.status==="FAILED")throw new Error(state.error_message||"分析失败");if(["COMPLETED","PARTIAL"].includes(state.status))break}data=await marketApi.opportunities(code)}setRows(data);if(data[0])await select(data[0].id)}catch(e){setError(e instanceof Error?e.message:"暂无可用分析")}finally{setLoading(false)}},[select]);useEffect(()=>{load(initialHs)},[initialHs,load]);function submit(e:FormEvent){e.preventDefault();const code=/^\d{4,10}$/.test(query.trim())?query.trim():"902620";setHs(code);load(code)}function chooseIso(iso:string){const row=rows.find(x=>x.destination_iso3===iso);if(row)select(row.id)}
return <><div className="workspace-head"><div>{heading&&<><div className="eyebrow">商品 → 国家</div><h1 className="page-title">全球市场分析</h1><p className="subtitle">HS {hs} · 原产地中国 · 最新完整贸易年度</p></>}</div><form className="compact-search" onSubmit={submit}><input aria-label="HS 编码" value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入 HS 编码"/><button className="primary" aria-label="搜索"><Search size={16}/></button></form></div>{loading?<div className="card loading"><RefreshCw size={20} className="animate-spin" style={{margin:"0 auto 12px"}}/>正在生成可解释市场分析…</div>:error?<div className="card error">{error}<br/><small>请确认 API 服务已启动。</small></div>:<><div className="workspace"><div className="card map-card"><WorldMap data={rows} selected={detail?.destination_iso3} onSelect={chooseIso}/><div className="map-legend">市场吸引力<div className="gradient"/>0&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;100</div></div><div className="card ranking"><div className="panel-title"><h2>市场排名</h2><span>{rows.length} 个国家/地区 · {rows[0]?.period_year}</span></div>{rows.map(row=><div key={row.id} className={`market-row ${detail?.id===row.id?"selected":""}`} onClick={()=>select(row.id)}><span className="ranknum">{String(row.rank).padStart(2,"0")}</span><div><span className="country">{row.country_name}</span><small>{money(row.import_value_usd)} · <span className={row.cagr_3y&&row.cagr_3y>=0?"positive":""}>{pct(row.cagr_3y)} 三年</span></small></div><div className="score">{row.score.toFixed(0)}</div><div className="coverage">覆盖度<br/><b>{row.coverage.toFixed(0)}%</b></div></div>)}</div></div>{detail&&<div className="lower-grid"><div className="card chart-card"><div className="chart-title"><div><h2>{detail.country_name}贸易趋势</h2><p>该国总进口与自中国进口</p></div><span className="status">{detail.period_year} 完整年度</span></div><TrendChart history={detail.history}/></div><aside className="card insight"><div className="eyebrow">为什么选择该市场？</div><div style={{display:"flex",gap:20,alignItems:"center"}}><div className="score-ring" style={{"--score":detail.score} as React.CSSProperties}><span>{detail.score.toFixed(0)}</span></div><div><strong>市场吸引力</strong><p style={{fontSize:13,color:"#607087",margin:"5px 0"}}>全球排名 #{detail.rank}<br/>覆盖度 {detail.coverage.toFixed(0)}%<br/>置信度 {detail.confidence_label === "HIGH" ? "高" : detail.confidence_label === "MEDIUM" ? "中" : detail.confidence_label === "LOW" ? "低" : "未知"}</p></div></div><ul className="reasons">{detail.reasons.map((r,i)=><li key={i}><b className={r.sentiment==="negative"?"negative":""}>{r.sentiment==="negative"?"−":"+"}</b>{r.text}</li>)}</ul><p style={{fontSize:12,color:"#77869a",marginTop:16}}>仅依据已记录证据生成，不构成销售预测。</p><Link className="detail-link" href={`/product/${hs}/country/${detail.destination_iso3}`}>查看完整市场机会 →</Link></aside></div>}</>}</>}
